### PR TITLE
remove hash_utils gem because of conflicts

### PR DESCRIPTION
**Pull request by dgertych-monterail**
I have encountered the same issue as @netDalek described in issue #1 
Could you review and accept this pull request?

### CODE REVIEW

**Comment by dgertych-monterail** [comment]
@martinkozak Any chance to get this PR merged?

**Comment by martinpoljak** [comment]
Hi, chance exists in each case, but I'm currently relocating to another place in the world, so I'll be able to do it unfortunately in several weeks.

**Comment by dgertych-monterail** [comment]
Better later than never. Good luck with relocation.

**Comment by martinpoljak** [comment]
Looks well. Merged.

**Pull request merged**
